name: Build
on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - "12"
          - "14"
          - "16"
    name: Node ${{ matrix.node }}
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y tcl-dev
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: npm
      - run: npm install
      - run: npm test
